language: node_js
node_js:
- 7.9.0
script:
- npm run build:prod
deploy:
  provider: openshift
  user: tbinetruy@gmail.com
  password:
    secure: GpQx8ChdHaiReanAi8KDbD7QoCiEiPgm4qM/pGyjEOVuSPk+FQRCyHBb1CRD3bcdOxX6AGTp14dQcL/8A6AH1gNHxMINlDTl8YwFCoag7IE3bkIKFGdLxoN9jLtZEj3ikmKgkCRh2nLVXCv+oARY/uFbVG1RPmfzHB7pX+unpb7rQkMyDlV/MG3XC7Ebx7x/9vQl3gBrexr0g/CaxhyWvqhJD+azWq/mS2A5bTIOQ2ySgZGxeI/Fha4x88LYxDGPyWcWAVUdw1GqkFyZR/Jn8borogHX4LwpfmqGe6ILLxJGNP11WvPn4Jkx10laVVKXRS/Q7Lxc+539DVvlz6hnmhPspIhFLopbzDb0Qgd6wMe+xv/eneCpeuvjKjk2CSF9Ud4TTcO5vctg0DJy2avg6/9BjbX4d6wsSPVYiegdP7AarsEZVNCdOfsXMFvat6s7l8kORv75C4fmoC0DVRhlZle/ukzpNR/BsKJQmxKltssbzSqUGtR8OEXGbjJRHMd+fm30W969MBjkKoR/7Zw7cYgwM7Dh61kcuy4UnA29xnFWXGjxVrSM6lo5Jj2jaKLKJkQH6ERnxImWGIjDTyndWzExUQjp1+h9FQvJljVaGNlCVLdbhfVJb2hJ2rqN/hZqwtuqdVDH9wS130UFUB95ct/1czLvLLukOmTRP4DOA9A=
  app: masas.fm
  domain: prod-masas.rhcloud.com
